### ISSUE TITLE
Checkbox causes parent container overflows

### ISSUE THREAD

**Issue by daelmaak** [sek-consulting/solid-ui#146]
## Reproducible
Chrome and Safari on Mac

## Description

In my cases it's happening when I have a container which has limited height and overflow auto or scroll, and there are solid-ui checkboxes inside.

The issue is that even though the overflow shouldn't display the overflowing content, which it doesn't, thanks to the checkboxes it still inflates the parent containers as if the overflow was `visible`.

You can see it on the vid below. I have a page with one column which has limited height and overflow scroll. I can scroll inside it just as excpected, but also it inflates the whole page and I can scroll even if there is no content below the fold.

https://github.com/user-attachments/assets/87b8362e-e057-4830-a0a7-ab3eeba12895

This was tricky to discover but I found that the Checkbox's `<input>` is to blame because of its inline styles:

```css
{
    border: 0px;
    clip: rect(0px, 0px, 0px, 0px);
    clip-path: inset(50%);
    height: 1px;
    margin: 0px -1px -1px 0px;
    overflow: hidden;
    padding: 0px;
    position: absolute; // <----- Hello there!
    width: 1px;
    white-space: nowrap;
}
```

The input is absolutely positioned but there is no positioned parent element for it inside the checkbox, nor does it specify its positioning. Not an expert, but I think this messes with the browser layout calcs.

## Solution

Now we could debate if WebKit or Kobalte is to blame but there is a very easy fix for you - putting `relative` on the root primitive, see for yourself:

https://github.com/user-attachments/assets/1ff855b7-fe2e-40f4-a2a6-f4efe11ed69d

Here is a repro repo https://github.com/daelmaak/solidui-checkbox-overflow

Happy to provide the PR as always.
